Changed bash_helpers.sh for bash_helpers in all scripts, although... i think i will move the most important things to another repo and delete all this...

diff --git a/bash_helpers b/bash_helpers
--- a/bash_helpers
+++ b/bash_helpers
@@ -1,4 +1,3 @@
-
 #!/bin/bash
 
 
@@ -12,7 +11,7 @@ abort()
         echo ""
     fi
 
-    if [[ "$0" == "$SHELL" ]];
+    if [[ "$0" == *bash ]] || [[ "$0" == *zsh ]];
     then
         return 1
     else
@@ -89,14 +88,14 @@ check_deps()
 	
 	REQUIRED_DEPS=$(echo "$REQUIRED_DEPS" | grep "  ${DEPENDS_STR}")
 	REQUIRED_DEPS=$(echo "$REQUIRED_DEPS" | sed "s/  ${DEPENDS_STR} //g")
-	REQUIRED_DEPS=$(echo "$REQUIRED_DEPS" | sed 's/<//g' | sed 's/>//g')
+	REQUIRED_DEPS=$(echo "$REQUIRED_DEPS" | sed "s/<//g" | sed "s/>//g")
 
 	RECOMMENDED_DEPS=$(echo "$RECOMMENDED_DEPS" | grep "  ${RECOMMENDED_STR}")
 	RECOMMENDED_DEPS=$(echo "$RECOMMENDED_DEPS" | sed "s/  ${RECOMMENDED_STR} //g")
-	RECOMMENDED_DEPS=$(echo "$RECOMMENDED_DEPS" | sed 's/<//g' | 's/>//g')
+	RECOMMENDED_DEPS=$(echo "$RECOMMENDED_DEPS" | sed "s/<//g" | "s/>//g")
 
 	ALL_DEPS="$REQUIRED_DEPS"
-	ALL_DEPS+="$RECOMMENDED_DEPS"
+	ALL_DEPS+=" $RECOMMENDED_DEPS"
 
     echo "$ALL_DEPS"
 }
@@ -249,6 +248,24 @@ is_newer()
 }
 
 
+is_running()
+{
+    EXEC_NAME="$1"
+
+    if ! [[ "$EXEC_NAME" == "" ]];
+    then
+        PROCESS_ID=$(pgrep -x $EXEC_NAME)
+        
+        if [[ "$?" == "0" ]];
+        then
+            echo -e "Yes\n"
+        fi
+    fi
+
+    echo -e "No\n"
+}
+
+
 lowercase()
 {
     if ! [[ "$1" == "" ]];
@@ -274,24 +291,6 @@ os_version()
         OS_VERSION=$(echo "$OS_INFO" | grep '^VERSION_CODENAME=')
         
         echo "$OS_VERSION" | cut -d '=' -f 2 
-    fi
-}
-
-
-path()
-{
-    if ! [[ "$TERMUX_VERSION" == "" ]];
-    then
-        echo "$PREFIX/opt/bin/bash_helpers.sh"
-        
-    else
-        if [[ "$HOME" == "/root" ]];
-        then
-            echo "/opt/bin/bash_helpers.sh"
-            
-        else
-            echo "$HOME/.local/bin/bash_helpers.sh"
-        fi
     fi
 }
 
@@ -359,21 +358,129 @@ uppercase()
 }
 
 
+install_helpers()
+{
+	if ! [[ -f "$HOME/.bashrc" ]] && [[ -v TERMUX_VERSION ]];
+    then
+        cp "$PREFIX/etc/bash.bashrc" "$HOME/.bashrc"
+    fi
+
+    if ! [[ -f "$HOME/.environment" ]];
+    then
+        touch "$HOME/.environment"
+    fi
+        
+    SCRIPT=$(realpath $0)
+    FILENAME=$(basename "$SCRIPT")
+
+    INSTALL_PATH=$(dirname $(path))
+
+    if [[ -v SUPER_USER ]];
+    then
+        PERMS="755"
+        SUDO="sudo"
+    else
+        PERMS="770"
+    fi
+
+    if ! [[ -d "$INSTALL_PATH" ]];
+    then
+        mkdir -p "$INSTALL_PATH"
+    fi
+
+    $SUDO cp $SCRIPT $INSTALL_PATH/
+    $SUDO chmod $PERMS "$INSTALL_PATH/${FILENAME}"
+
+    if [[ "$?" == "0" ]];
+    then
+		if [[ -d "$HOME/.envs" ]] && ! [[ -f "$HOME/.envs/bash_helpers" ]];
+		then
+		    URL="https://raw.githubusercontent.com/aribrew/bash_scripting"
+            URL+="/refs/heads/main/.bash_helpers.env"
+
+			curl -LO $URL
+
+			if [[ "$?" == "0" ]];
+			then
+			    mv .bash_helpers.env $HOME/.envs/bash_helpers
+			fi
+
+			if [[ -f ".bash_helpers.env" ]];
+			then
+			    rm ".bash_helpers.env"
+			fi
+		fi
+    fi
+}
+
+
+path()
+{
+    if ! [[ "$TERMUX_VERSION" == "" ]];
+    then
+        echo "$PREFIX/opt/bin/bash_helpers"
+        
+    else
+        if [[ "$HOME" == "/root" ]];
+        then
+            echo "/opt/bin/bash_helpers"
+            
+        else
+            echo "$HOME/.local/bin/bash_helpers"
+        fi
+    fi
+}
+
+
+update_helpers()
+{
+	cd /tmp
+	
+	URL="https://raw.githubusercontent.com/aribrew/bash_scripting"
+	URL+="/refs/heads/main/bash_helpers"
+	
+	echo -e "Downloading latest bash_helpers ..."
+	echo -e "-----------------------------------"
+	    
+	curl -LO $URL
+	
+	if [[ "$?" == "0" ]];
+	then
+	    INSTALL_PATH=$(path)
+	
+	    cp -u bash_helpers "$INSTALL_PATH"
+	
+	    if [[ "$?" == "0" ]];
+	    then
+	        echo -e "Done!\n"
+	    else
+	        abort "Something is wrong. Unable to update local script.\n"
+	    fi
+	else
+	    rm /tmp/bash_helpers
+	    abort "Failed!"
+	fi
+}
+
+
 helpers_usage()
 {
-    echo "source bash_helpers.sh"
+    echo "source bash_helpers"
     echo ": Loads the functions in the current shell."
     echo ""
-    echo "bash_helpers.sh --install"
+    echo "bash_helpers --cmds"
+    echo ": List all available exported commands."
+    echo ""
+    echo "bash_helpers --install"
     echo ": Installs the helpers."
     echo "  - If NOT using sudo, installs in ~/.local/bin"
     echo "  - Otherwise installs in /opt/bin"
     echo ""
-    echo "bash_helpers.sh --path"
+    echo "bash_helpers --path"
     echo ": Tells where the helpers are/would be installed."
     echo ""
-    echo "bash_helpers.sh --cmds"
-    echo ": List all available exported commands."
+    echo "bash_helpers --update"
+    echo ": Updates installed script."
     echo ""
 }
 
@@ -383,6 +490,7 @@ then
     export -f abort
     export -f ask_for
     export -f ask_yn
+    export -f check_deps
     export -f check_if_admin
     export -f check_port
     export -f check_script
@@ -434,54 +542,9 @@ then
     
 elif [[ "$1" == "--install" ]];
 then
-    if ! [[ -f "$HOME/.bashrc" ]] && [[ -v TERMUX_VERSION ]];
-    then
-        cp "$PREFIX/etc/bash.bashrc" "$HOME/.bashrc"
-    fi
+    install_helpers
 
-    if ! [[ -f "$HOME/.environment" ]];
-    then
-        touch "$HOME/.environment"
-    fi
-        
-    SCRIPT=$(realpath $0)
-    FILENAME=$(basename "$SCRIPT")
-
-    INSTALL_PATH=$(dirname $(path))
-
-    if [[ -v SUPER_USER ]];
-    then
-        PERMS="755"
-        SUDO="sudo"
-    else
-        PERMS="770"
-    fi
-
-    if ! [[ -d "$INSTALL_PATH" ]];
-    then
-        mkdir -p "$INSTALL_PATH"
-    fi
-
-    $SUDO cp $SCRIPT $INSTALL_PATH/
-    $SUDO chmod $PERMS "$INSTALL_PATH/${FILENAME}"
-
-    if [[ "$?" == "0" ]];
-    then
-        grep -q "$INSTALL_PATH" "$HOME/.environment"
-
-        if ! [[ "$?" == "0" ]];
-        then
-            echo "export PATH=$INSTALL_PATH:\$PATH" >> "$HOME/.environment"
-
-            grep -q "\$HOME/.environment" "$HOME/.bashrc"
-
-            if [[ "$?" == "1" ]];
-            then
-                echo "source \$HOME/.environment" >> "$HOME/.bashrc"
-            fi
-        fi
-        
-        echo "Bash helpers installed to $INSTALL_PATH."
-        echo ""
-    fi
+elif [[ "$1" == "--update" ]];
+then
+    update_helpers
 fi
