Moving things to bash_helpers. The folder with all WINE things will be winenv now.

diff --git a/cmds/win_start b/cmds/win_start
--- a/cmds/win_start
+++ b/cmds/win_start
@@ -1,84 +1,17 @@
 #!/bin/bash
 
-abort()
-{
-    MESSAGE=$1
+BASH_HELPERS="/opt/bin/bash_helpers"
 
-    if ! [ "$MESSAGE" == "" ];
-    then
-        echo "$MESSAGE"
-        echo ""
-    fi
+if ! [ -f "$BASH_HELPERS" ];
+then
+    echo "Cannot find '$BASH_HELPERS'."
+    echo ""
 
     exit 1
-}
-
-
-check_exec_arch()
-{
-    EXEC_FILE=$1
-
-    echo "Checking if file '$EXEC_FILE' is a Windows executable..."
-
-    FILE_TYPE=$(exec_type "$EXEC_FILE")
-
-    if [ "$FILE_TYPE" == "windows-i386" ];
-    then
-        export WINE32_NEEDED=1
-
-        echo "Want to launch a Windows 32 bit executable."
-        echo ""
-
-    elif [ "$FILE_TYPE" == "windows-amd64" ];
-    then
-        export WINE64_NEEDED=1
-
-        echo "Want to launch a Windows 64 bit executable."
-        echo ""
-
-    else
-        abort "The given file isn't a Windows 32 or 64 bit executable."
-    fi
-}
-
-
-exec_type()
-{
-    EXEC=$1
-    FILE_TYPE=$(file -L "$EXEC")
-
-    echo ${FILE_TYPE} | grep "ELF 32-bit" > /dev/null
-
-    if [ "$?" == "0" ];
-    then
-        echo "linux-i386"
-        echo ""
-    else
-        echo ${FILE_TYPE} | grep "ELF 64-bit" > /dev/null
-
-        if [ "$?" == "0" ];
-        then
-            echo "linux-amd64"
-            echo ""
-        else
-            echo ${FILE_TYPE} | grep "PE32 executable" > /dev/null
-
-            if [ "$?" == "0" ];
-            then
-                echo "windows-i386"
-                echo ""
-            else
-                echo ${FILE_TYPE} | grep "PE32+ executable" > /dev/null
-
-                if [ "$?" == "0" ];
-                then
-                    echo "windows-amd64"
-                    echo ""
-                fi
-            fi
-        fi
-    fi
-}
+    
+else
+    source "$BASH_HELPERS"
+fi
 
 
 usage()
