Cleaning a bit the bash_helpers thing.

diff --git a/cmds/win_start b/cmds/win_start
--- a/cmds/win_start
+++ b/cmds/win_start
@@ -1,16 +1,11 @@
 #!/bin/bash
 
-BASH_HELPERS="/opt/bin/bash_helpers.sh"
+source bash_helpers.sh
 
-if ! [[ -f "$BASH_HELPERS" ]];
+if ! [[ -v BASH_HELPERS_LOADED ]];
 then
-    echo "Cannot find '$BASH_HELPERS'."
-    echo ""
-
+    echo -e "BASH Helpers not found in PATH. Install them first.\n"
     exit 1
-    
-else
-    source "$BASH_HELPERS"
 fi
 
 
