Updated BASH helpers messages. Winedump added to aliases.

diff --git a/cmds/aux/isolabel b/cmds/aux/isolabel
--- a/cmds/aux/isolabel
+++ b/cmds/aux/isolabel
@@ -1,5 +1,13 @@
 #!/bin/bash
 
+source bash_helpers.sh
+
+if ! [[ -v BASH_HELPERS_LOADED ]];
+then
+    echo -e "BASH helpers not found in PATH. Install it first.\n"
+    exit 1
+fi
+
 if ! [[ "$1" == "" ]] && [[ -f "$1" ]];
 then
     ISO=$1
